name: Docker

on:
  push:
    branches: [ "main" ]
    tags: [ "*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  docker:
    uses: famedly/github-workflows/.github/workflows/docker.yml@main
    with:
      push: ${{ github.event_name != 'pull_request' }} # Always build, don't publish on pull requests
      registry_user: ${{ vars.REGISTRY_USER }}
      registry: registry.famedly.net/docker-oss
      image_name: synapse-usage-exporter
      file: docker/Dockerfile
    secrets: inherit
