name: Python

on:
  push:
    branches: [ "main" ]
    tags: [ "*" ]
  pull_request:
    branches: [ "*" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Lint and format check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.9", "3.10", "3.11" ]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Formatting
        uses: famedly/black@stable
        with:
          options: "--check --verbose"

      - name: Prepare lint
        shell: bash
        run: echo PYTHON_TARGET="py${{ matrix.python-version }}" | sed 's/\.//g' >> $GITHUB_ENV

      - name: Lint
        uses: chartboost/ruff-action@491342200cdd1cf4d5132a30ddc546b3b5bc531b
        with:
          args: check --target-version ${{ env.PYTHON_TARGET }}
